### ISSUE TITLE
Client's train method

### ISSUE THREAD

**Issue by jarumil** [CharlieDinh/pFedMe#18]
Hi, I have a question about the train method in the clients. Normally, in each epoch the complete dataset is trained using batches, but I have seen in your code that in each epoch, only a single batch is trained. Is this correct? Best regards.

![error](https://user-images.githubusercontent.com/23283387/132997512-8477f144-adb6-4c28-afa4-d2ff1269d4cd.png)

**Comment by CharlieDinh** [comment]
Hi, following the algorithm, and doing stochastic, for each epoch, we only sample one mini-batch, when the number of the local epoch is large enough, it will cover all batches in training data. 
So by varying the number of the local epoch, actually it is similar to one epoch train complete data.

**Comment by jarumil** [comment]
Thank you very much for your prompt response. Perfect, I understand what you are saying.
