### ISSUE TITLE
A question about train_one_step() method.

### ISSUE THREAD

**Issue by sshpark** [CharlieDinh/pFedMe#4]
https://github.com/CharlieDinh/pFedMe/blob/96863e05e799fb6ad23248c63824b0381d2bec11/FLAlgorithms/users/userperavg.py#L66
Hi CharlieDinh, I' m Sorry to take up your time. Can you tell me why `self.get_next_test_batch()` is used to do the update in the first step and then `self.get_next_train_batch()` is used to do the update in the second step? Can I do both updates with `self.get_next_train_batch()` ?

**Comment by hesetone** [comment]
@sshpark , se se fa dou, orz ......

**Comment by hesetone** [comment]
> https://github.com/CharlieDinh/pFedMe/blob/96863e05e799fb6ad23248c63824b0381d2bec11/FLAlgorithms/users/userperavg.py#L66
> 
> 
> Hi CharlieDinh, I' m Sorry to take up your time. Can you tell me why `self.get_next_test_batch()` is used to do the update in the first step and then `self.get_next_train_batch()` is used to do the update in the second step? Can I do both updates with `self.get_next_train_batch()` ?

se se fa dou, orz, ......

**Comment by CharlieDinh** [comment]
Hi Sshpark, Sorry for the late reply. I've seen your comment yet. 
Actually, PerFedAvg requires a one-step update using the test data. So both should be get_next_test_batch. I updated the code.

**Comment by sshpark** [comment]
> Hi Sshpark, Sorry for the late reply. I've seen your comment yet.
> Actually, PerFedAvg �requires a one-step update using the test data. So both should be get_next_test_batch. I updated the code.

Thank you very much for your answer!
