### ISSUE TITLE
Why does FedAvg only train on 1 batch in each local epoch?

### ISSUE THREAD

**Issue by mengcz13** [CharlieDinh/pFedMe#6]
https://github.com/CharlieDinh/pFedMe/blob/5060b3415b57a0d1f556cb119ffacfa37f3fc4ba/FLAlgorithms/users/useravg.py#L32

This disagrees with the original FederatedAveraging algorithm in ([https://arxiv.org/pdf/1602.05629.pdf](https://arxiv.org/pdf/1602.05629.pdf)), where the local model should be trained on all batches in each local epoch.

pFedMe and peravg also have the same behavior. Is there any reason for training with only 1 batch of data in each local epoch? Thanks!

**Comment by CharlieDinh** [comment]
Hi. It is for a fair comparison with pFedme and Per-FedAvg as in the algorithm here we use only one-mini batch at each local iteration to train the personalized model from the global model. Actually, assume that each client has the data size of (number_batch* batch_size). So, for original FederatedAveraging they use for example 2 local_epoch to train all batch (2*number_batch iterations in total for local training), it will similar to you run 2* number_batch local epochs (each epoch only train 1 batch) in our code, so by varying the number of local updates, it will be similar with the original paper.

**Comment by mengcz13** [comment]
Got it. Thanks for your explanation!
